### PR TITLE
adding babel-preset-react and babel-preset-stage-0 as dependencies

### PR DESCRIPTION
**Pull request by zulucoda**
This fixes an issue when using react-redux-mock with npm.

Because `babel-preset-react` and `babel-preset-stage-0` was added as a devDependencies they were not installed in the node-modules folder. Therefore this results in a babel preset error when running test. The reason for this error is because `babel-preset-react` and `babel-preset-stage-0` are missing.

**Error Details**
ReferenceError: [BABEL] /node_modules/react-redux-mock/lib/index.js: Unknown option: /node_modules/react/index.js.Children. Check out http://babeljs.io/docs/usage/options/ for more informa
tion about options.                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                            
    A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:                                                                                                                                          
                                                                                                                                                                                                                                                                            
    Invalid:                                                                                                                                                                                                                                                                
      `{ presets: [{option: value}] }`                                                                                                                                                                                                                                      
    Valid:                                                                                                                                                                                                                                                                  
      `{ presets: [['presetName', {option: value}]] }`                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                            
    For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options.

### CODE REVIEW

**Comment by khanghoang** [comment]
@zulucoda thanks for the PR. I will check it out today.

**Comment by khanghoang** [comment]
🎉🎊

**Comment by zulucoda** [comment]
awesome thanks @khanghoang 👍

**Comment by zulucoda** [comment]
@khanghoang may you kindly also publish to npm as well? thanks 💯

**Comment by khanghoang** [comment]
I just did 🎉

**Comment by zulucoda** [comment]
thanks mate, this is an awesome module. thanks again for creating it 👌

**Pull request merged**
